[feat] Add dummy implementation for portals as an additional RDMA provider

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -85,7 +85,7 @@ function usage() {
 	echo " --with-ublk               Build ublk library."
 	echo " --without-ublk            No path required."
 	echo " --with-rdma[=PROVIDER]    Build RDMA transport for NVMf target and initiator."
-	echo " --without-rdma            Accepts optional RDMA provider name. Can be \"verbs\" or \"mlx5_dv\"."
+	echo " --without-rdma            Accepts optional RDMA provider name. Can be \"verbs\" or \"mlx5_dv\" or \"portals\"."
 	echo "                           If no provider specified, \"verbs\" provider is used by default."
 	echo " --with-fc[=DIR]           Build FC transport for NVMf target."
 	echo " --without-fc              If an argument is provided, it is considered a directory containing"
@@ -872,10 +872,17 @@ if [[ $sys_name != "Linux" ]]; then
 fi
 
 if [ "${CONFIG[RDMA]}" = "y" ]; then
-	if [[ ! "${CONFIG[RDMA_PROV]}" == "verbs" ]] && [[ ! "${CONFIG[RDMA_PROV]}" == "mlx5_dv" ]]; then
-		echo "Invalid RDMA provider specified, must be \"verbs\" or \"mlx5_dv\""
+
+  #gesalous
+  if [[ ! "${CONFIG[RDMA_PROV]}" == "verbs" ]] && [[ ! "${CONFIG[RDMA_PROV]}" == "mlx5_dv" ]] && [[ ! "${CONFIG[RDMA_PROV]}" == "portals" ]]; then
+		echo "Invalid RDMA provider specified, must be \"verbs\", \"mlx5_dv\", or \"portals\""
 		exit 1
 	fi
+  #original
+  #if [[ ! "${CONFIG[RDMA_PROV]}" == "verbs" ]] && [[ ! "${CONFIG[RDMA_PROV]}" == "mlx5_dv" ]]; then
+	# echo "Invalid RDMA provider specified, must be \"verbs\" or \"mlx5_dv\""
+	# exit 1
+	#fi
 
 	if ! echo -e '#include <infiniband/verbs.h>\n#include <rdma/rdma_verbs.h>\n' \
 		'int main(void) { return 0; }\n' \
